# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/41561b0d-d78e-407d-a3ba-d355e77abf46";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/41561b0d-d78e-407d-a3ba-d355e77abf46";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/41561b0d-d78e-407d-a3ba-d355e77abf46";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/fast" =
    { device = "/dev/disk/by-uuid/af713576-a6c0-4297-a583-6feb02694bc9";
      fsType = "btrfs";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/c20e0a38-2e8b-4e6b-ad73-c903cbe41d5a";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6746-1633";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
